- hosts: webservers
  become: true
  become_user: root
  vars_files:
    - myvariables.yml
  tasks:
    - name: Install multiple packages on host server
      package: name={{item}} state=present
      loop:
        - git
        - docker
        - nano
        - tree
    - name: Start Docker service
      service: name=docker state=started
    - name: Build the dockerfile
      command: docker build -t {{image_name}} .
    - name: run the image to launch a container
      command: docker run -d -P {{image_name}}
